name: Build JAR with Maven and Oracle JDK 23

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Oracle JDK 23
      - name: Set up Oracle JDK 23
        uses: actions/setup-java@v4.5.0
        with:
          distribution: oracle
          java-version: 23

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the JAR file with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Create an executables folder
      - name: Create executables folder
        run: mkdir -p executables

      # Step 6: Move the JAR file to the executables folder
      - name: Move JAR file
        run: mv target/*.jar executables/

      # Step 7: Commit and push the JAR file to the repository
      - name: Commit and push JAR file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add executables/
          git commit -m "Add built JAR file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
